name: Declenche Azure DevOps Pipeline

on:
    workflow_dispatch:

jobs:

  aZDO:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://pierrc.visualstudio.com/Hybrid-AzDO-GitHub'
          azure-pipeline-name: 'Hybrid-AzDO-GitHub' # name of the Azure pipeline to be triggered
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
          #azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
